name: barc-blanket-env

channels:
  - conda-forge
  - defaults

dependencies:
  - numpy
  - pandas
  - matplotlib
  - openmc
  - dash
  - plotly
  - pip
  - warnings
  - yaml ==0.2.5
  - optuna ==3.5.0
  - scipy ==1.11.4
  - pytest
  - pip:
    - openmc_regular_mesh_plotter
